datasets:
  augmentation:
    image_shape: []  # keep native resolution (no resize)
  test:
    dataset: ['ncdb']
    path: ['/workspace/data/ncdb-cls-1920x1536-img-only']
    split: ['splits/combined_val.json']
    mask_file: ['binary_mask.png']
    use_mask: [false]
arch:
  validate_first: false
  eval_during_training: false
  eval_subset_size: 0
